### ISSUE TITLE
Contents API Checklist

### ISSUE THREAD

**Issue by jdetle** [nteract/rx-jupyter#26]
Hi, I'm making this checklist based off of [IPEP 27](https://github.com/ipython/ipython/wiki/IPEP-27:-Contents-Service), please let me know if I'm forgetting or misunderstanding anything. 

Actions specified in the IPEP 27
-----
- [x] Create a new file (named `create`)
- [x] Upload a file 
- [x] Copy a file
- [x] List contents (`get` lists contents of a file or a directory)
- [x] Get an existing file (named `get`)
- [x] Rename a file
- [x] Save a file
- [x] Delete file (named `remove`)
- [x] List checkpoints
- [x] Create a checkpoint
- [x] Restore from a checkpoint
- [x] Delete a checkpoint

**Comment by jdetle** [comment]
@rgbkrk, does this look right to you?

**Comment by rgbkrk** [comment]
As long as we're cross-referencing with:

[The swagger doc](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml) for the technical description

and

[jupyter/notebook](https://github.com/jupyter/notebook) for the actual implementation

then we're good to go.

List appears pretty solid to me. Now that we've refactored our requests it should be a lot easier to implement the rest of these with good API semantics.
